global using ApiMovies;
global using ApiMovies.Background;
global using ApiMovies.Common;
global using ApiMovies.Common.Interfaces;
global using ApiMovies.Common.Service;
global using ApiMovies.Data.Configs;
global using ApiMovies.Data.Initialization;
global using ApiMovies.Logger;
global using ApiMovies.Models;
global using ApiMovies.Models.ApiResponse;
global using ApiMovies.Routes;
global using ApiMovies.Utils;
global using Microsoft.AspNetCore.Http.Json;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.OpenApi.Models;
global using Newtonsoft.Json;
global using Serilog;
global using Serilog.Events;
global using Swashbuckle.AspNetCore.Annotations;
global using System.Net;
global using System.Text.Json.Serialization;
global using HomeMetadataMessages = ApiMovies.Utils.Messages.EndpointMetadata.HomeEndpoint;
global using PopularMetadataMessages = ApiMovies.Utils.Messages.EndpointMetadata.PopularEndpoint;
global using SearchMetadataMessages = ApiMovies.Utils.Messages.EndpointMetadata.SearchEndpoint;
global using TrendingMetadataMessages = ApiMovies.Utils.Messages.EndpointMetadata.TrendingEndpoint;